//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long CommentsId { get; set; }
        public string WriterName { get; set; }
        public string Email { get; set; }
        public string subject { get; set; }
        public string Message { get; set; }
        public Nullable<long> PostId { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
