//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Post
    {
        public long Id { get; set; }
        public string WriterName { get; set; }
        public string DatedPost { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        [AllowHtml]
        public string Text { get; set; }
        public string Img { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> Viewed { get; set; }
        public string quotes { get; set; }
        [AllowHtml]
        public string TextsecondPart { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
